In [ ]:
import os
import tensorflow as tf

# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y

x = tf.random.normal((2, 2))

# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

# Reshaping
x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])


In [1]:
import os
import tensorflow as tf

# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [2]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [3]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [4]:
x = tf.ones((4, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [5]:
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [6]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.72494733 0.16535103]
 [0.5210756  0.67935205]], shape=(2, 2), dtype=float32)


In [8]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
# print(x)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

tf.Tensor(
[[ 0.15292363 -0.12395219 -1.53211284]
 [-0.66273671  0.09230766 -1.06834745]
 [-0.27161258  1.19048142  1.72551334]], shape=(3, 3), dtype=float64)


In [9]:
x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)


tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [10]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [11]:
z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)
print(z)
z = x ** 5
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [12]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[ 1.9014027  1.4995092]
 [-2.4493105 -3.7342882]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.9014027  1.4995092]
 [-2.4493105 -3.7342882]], shape=(2, 2), dtype=float32)


In [13]:
x = tf.random.normal((2, 2))

# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [15]:
indices = tf.constant([0, 4])
x_indices = tf.gather(x, indices)
print(x_indices)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [17]:
print(x[3])

tf.Tensor(2, shape=(), dtype=int32)


In [18]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

# Reshaping
x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [19]:
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
